name: Amnezia-UI v3.1 CI
on:
  push:
    branches: [ main ]
    paths:
      - 'amnezia-ui-universal-v31.sh'
      - 'install-universal-v31.sh'
      - '.github/workflows/github-actions-v31.yml'
      - 'README.md'
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: |
            *.md
  package:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Create tarball
        run: |
          mkdir -p release/amnezia-ui
          cp amnezia-ui-universal-v31.sh release/amnezia-ui/amnezia-ui
          chmod 0755 release/amnezia-ui/amnezia-ui
          tar -czf asuswrt-merlin-amnezia-ui.tar.gz -C release amnezia-ui
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: asuswrt-merlin-amnezia-ui
          path: asuswrt-merlin-amnezia-ui.tar.gz
